### ISSUE TITLE
[Bug]: Documentation out-of-date.

### ISSUE THREAD

**Issue by HeySteets** [gravitl/netmaker-docs#95]
### What happened?

With the new Caddy-based release, the quick-Install documentation for Netmaker on readthedocs.io is now out-of-date, as it fails to mention acquiring the Caddyfile and the necessary modifications to make to it. Following the instructions verbatim results in the dashboard URL displaying the default Caddy webpage.

A proper installation can still be completed by reverse-engineering the necessary steps from the 5-minute install script, but the "recommended" method of setup in the docs doesn't appear to be working.

### Version

v0.17.0

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by afeiszli** [comment]
Docs are now upgraded.
